### PR TITLE
Added PHP-CS-Fixer

### PR DESCRIPTION
**Pull request by OskarStark**
Rebase of #48

### CODE REVIEW

**Comment by OskarStark** [comment]
I will apply https://github.com/amzn/amazon-pay-sdk-php/pull/48/commits/3cb60f74127aba9903e0a51a3ff8fd75ab092ef2 after this PR is merged

**Comment by OskarStark** [comment]
any news here?

**Comment by bjguillot** [comment]
We will evaluate your pull request when we prepare the next revision to the PHP SDK release.  It may or may not make the next release due to the number of source code changes that need to be reviewed and tested in this pull request.  Thank you for helping us drive the code base to better and cleaner PHP coding standards.

**Comment by OskarStark** [comment]
Ok, thank you for your feedback, let me know if i can support you 👍

**Comment by ejegg** [comment]
@OskarStark how about just committing the results of running php-cs-fixer? It's a tool that shouldn't need to be applied more than once, if the maintainers are vigilant. At the least, I think the .cache file shouldn't be tracked in git.

@bjguillot One easy way to check all these code style changes is to check out this revision and run
`git diff -w 399c7ee7af..HEAD`
The "-w" means ignore whitespace changes, and just gives you a list of changes that could affect functionality.

**Pull request closed without merging**
